# Configuration for probot-no-response - https://github.com/probot/no-response
# Number of days of inactivity before an Issue is closed for lack of response
daysUntilClose: 14
# Label requiring a response (applied to issues needing user input)
responseRequiredLabel: "awaiting user reply"
# Comment to post when closing an Issue for lack of response. Set to `false` to disable
closeComment: |
  This issue has been automatically closed because we haven't received a response
  to our request for more information after 14 days.

  To help us investigate further, please provide the additional details we asked for.
  Once you add a comment with the required information, we can reopen this issue.

  Thank you for your understanding!
