# This workflow configures the user-statistician with the
# dark-dimmed color theme, but otherwise uses all of
# the defaults. It is configured on a daily schedule at 3am.

name: User Statistician

permissions:
  contents: write

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ main, master ]
    paths: [ '.github/workflows/user-statistician.yml' ]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Generate User Stats Image
      uses: cicirello/user-statistician@6a7e459d1174b5822afa99a7c6acccf376cb2eb1 # v1.25.0
      with:
        colors: dark
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
